Repository ros/diagnostics, pull requests merged in 2025-05, with the labels that each got.

#399 diagnostic_updater: Added documentation of the Python interface.
  diagnostic_updater/.gitignore
  diagnostic_updater/doc/conf.py
  diagnostic_updater/doc/index.rst
  diagnostic_updater/mainpage.dox
  diagnostic_updater/package.xml
  diagnostic_updater/rosdoc.yaml
  diagnostic_updater/src/diagnostic_updater/__init__.py
  diagnostic_updater/src/diagnostic_updater/_diagnostic_status_wrapper.py
  diagnostic_updater/src/diagnostic_updater/_diagnostic_updater.py
  diagnostic_updater/src/diagnostic_updater/_publisher.py
  diagnostic_updater/src/diagnostic_updater/_update_functions.py
Labels: ros1

#282 Fix two code-analyser bugs
  diagnostic_aggregator/src/aggregator.cpp
  diagnostic_aggregator/src/aggregator_node.cpp
Labels: ros1

#126 Add DowngradeAnalyser for reporting non-critical errors
  diagnostic_aggregator/CMakeLists.txt
  diagnostic_aggregator/analyzer_plugins.xml
  diagnostic_aggregator/include/diagnostic_aggregator/downgrade_analyzer.h
  diagnostic_aggregator/src/downgrade_analyzer.cpp
Labels: ros1

#474 Kilted dep fix
  diagnostic_aggregator/CMakeLists.txt
  diagnostic_remote_logging/CMakeLists.txt
  diagnostic_updater/CMakeLists.txt
  self_test/CMakeLists.txt
Labels: ros2

#478 Another mergify rule
  .github/mergify.yml
Labels: ros2

#480 Automerge
  .backportrc.json
  .github/mergify.yml
Labels: ros2

#482 [ros2-jazzy] Add mergify rules (#477)
  .github/mergify.yml
Labels: automerge

#483 [ros2-kilted] Add mergify rules (#477)
  .github/mergify.yml
Labels: automerge

#484 Listing all checks for automerge
  .backportrc.json
  .github/mergify.yml
Labels: ros2

#485 [ros2-humble] Another mergify rule (#478)
  .github/mergify.yml
Labels: automerge

#486 [ros2-jazzy] Another mergify rule (#478)
  .github/mergify.yml
Labels: automerge

#487 [ros2-kilted] Another mergify rule (#478)
  .github/mergify.yml
Labels: automerge

#488 Checks for all distros
  .github/mergify.yml
Labels: ros2

#489 [ros2-humble] Automerge (#480)
  .backportrc.json
  .github/mergify.yml
Labels: automerge

#490 [ros2-jazzy] Automerge (#480)
  .backportrc.json
  .github/mergify.yml
Labels: automerge

#491 [ros2-kilted] Automerge (#480)
  .backportrc.json
  .github/mergify.yml
Labels: automerge

#496 [ros2-humble] Listing all checks for automerge (#484)
  .backportrc.json
  .github/mergify.yml
Labels: automerge

#497 [ros2-jazzy] Listing all checks for automerge (#484)
  .backportrc.json
  .github/mergify.yml
Labels: automerge

#498 [ros2-kilted] Listing all checks for automerge (#484)
  .backportrc.json
  .github/mergify.yml
Labels: automerge

#500 [ros2-humble] Checks for all distros (#488)
  .github/mergify.yml
Labels: automerge

#501 [ros2-jazzy] Checks for all distros (#488)
  .github/mergify.yml
Labels: automerge

#502 [ros2-kilted] Checks for all distros (#488)
  .github/mergify.yml
Labels: automerge

#400 fix: replace deprecated MessageUniquePtr
  diagnostic_updater/include/diagnostic_updater/publisher.hpp
Labels: enhancement, ros2

#503 [ros2-kilted] fix: replace deprecated MessageUniquePtr (#400)
  diagnostic_updater/include/diagnostic_updater/publisher.hpp
Labels: automerge

#508 [ros2-kilted] Use target_link_libraries instead of ament_target_dependencies (#507)
  diagnostic_remote_logging/CMakeLists.txt
  diagnostic_updater/CMakeLists.txt
  self_test/test/CMakeLists.txt
Labels: automerge

#505 fix: Missing link to libcurl
  diagnostic_remote_logging/CMakeLists.txt
Labels: bug, ros2
